### ISSUE TITLE
ParameterJuMP and direct mode

### ISSUE THREAD

**Issue by jd-lara** [JuliaStochOpt/ParameterJuMP.jl#58]
Is it possible to use ParameterJuMP and direct mode? How would that look like if we wanted to implement it?

**Comment by blegat** [comment]
We don't assume anything on the MOI backend so I think it works on direct mode. You just have to do

```julia
model = direct_model(optimizer)
enable_parameters(model)
```

**Comment by jd-lara** [comment]
This works, thanks.
