### ISSUE TITLE
Mutable Arithmetics

### ISSUE THREAD

**Issue by joaquimg** [JuliaStochOpt/ParameterJuMP.jl#64]
Follow https://github.com/JuliaOpt/JuMP.jl/pull/2107 here.

@blegat do you have suggestions on how to proceed. I can try to fix this one.

**Comment by joaquimg** [comment]
cc @jd-lara

**Comment by jd-lara** [comment]
I can help with this next week

**Comment by blegat** [comment]
`destructive_add!` can be replaced most of the time by `MA.mutable_operate!(MA.add_mul, ...)`. However, you should not define `MA.mutable_operate!` when it does not stores the result in the first argument by modifying it. In this case, MA will not redirect to `MA.mutable_operate!`. Thanks to this, some `destructive_add!` call can just be removed. For instance, these ones can just be removed:
https://github.com/JuliaStochOpt/ParameterJuMP.jl/blob/c165e0fc389e90b6187ac8f2cc2ff498ec2ad58c/src/mutable_arithmetics.jl#L11-L32
as you cannot modify a number, variable or parameter to hold the result of the operation.
